# SCREEN CONSTANTS
WIDTH = 1280
HEIGHT = 720

# PHYSICS CONSTANTS
GRAVITY = 0.5
COLLISION_TOLERANCE = 15
COMBAT_TOLERANCE = 10

HEALTH_BAR_HEIGHT = 10
HEALTH_BAR_WIDTH = 50

# UNIVERSAL CONSTANTS
HEALTH = 100
FRICTION = -0.12
PLATFORM_GAP = 230

BULLET_DISTANCE = 200
BATARANG_RANGE = 650
BATARANG_SPEED = 15
BATARANG_DAMAGE = 15

# PLAYER CONSTANTS
PLAYER_DAMAGE = 2
PLAYER_ACC = 0.75
PLAYER_JUMP = -11
PLAYER_MAX_FALL_SPEED = 10

PLAYER_BULLET_SPEED = 500
PLAYER_BULLET_DAMAGE = 2

PLAYER_BAR_WIDTH = 200
PLAYER_BAR_HEIGHT = 50
PLAYER_BAR_OUTLINE = 'player_health_bar.png'

# MELEE ENEMY CONSTANTS
MELEE_ENEMY_DAMAGE = 2
MELEE_ENEMY_ACC = 0.4
MELEE_ENEMY_JUMP = -11
MELEE_ENEMY_MAX_FALL_SPEED = 10

KNIFE_RANGE = 300
MELEE_ENEMY_BULLET_SPEED = 500
MELEE_ENEMY_KNIFE_SPEED = 10
MELEE_ENEMY_KNIFE_DAMAGE = 10
MELEE_ENEMY_BULLET_DAMAGE = 2

MELEE_ENEMY_BAR_WIDTH = 200
MELEE_ENEMY_BAR_HEIGHT = 50
MELEE_ENEMY_BAR_OUTLINE = 'player_health_bar.png'


# COLORS
WHITE = (255, 255, 255)
BLACK = (0, 0, 0)
RED = (255, 0, 0)
GREEN = (0, 255, 0)
YELLOW = (255, 255, 0)
